### ISSUE TITLE
[BUG] Testing issue tracker

### ISSUE THREAD

**Issue by ImpactRedmi** [Share-Impact/Impact-Issues#1]
**Describe the bug**
This is a trial issue to test new issue tracker with github

**To Reproduce**
None

**Expected behavior**
Ease of posting and tracking issue

**Screenshots**
None

**Smartphone (please complete the following information):**
 - OS: [Android/IOS] Android
 - Version [e.g. v2.10.9] NA

**Additional context**
NA

**Comment by sagrgpt** [comment]
Work In Progress.

**Comment by ImpactRedmi** [comment]
Still facing the issue. Reopen request
